// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANiCfinhpPXZnecaDBg482lFGtShSUUSI',
    appId: '1:264102339770:web:9527660b5d9be7eecbce83',
    messagingSenderId: '264102339770',
    projectId: 'dormfoodapp',
    authDomain: 'dormfoodapp.firebaseapp.com',
    storageBucket: 'dormfoodapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGHIH6GcRzKijaPWEHz0ADMovF_vyt_6M',
    appId: '1:264102339770:android:29545f0f90de9e27cbce83',
    messagingSenderId: '264102339770',
    projectId: 'dormfoodapp',
    storageBucket: 'dormfoodapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5gtBozMIxQOsoBHZyJTipsP4wD85y4hc',
    appId: '1:264102339770:ios:77c544b28c80de83cbce83',
    messagingSenderId: '264102339770',
    projectId: 'dormfoodapp',
    storageBucket: 'dormfoodapp.firebasestorage.app',
    iosBundleId: 'com.example.dormfood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5gtBozMIxQOsoBHZyJTipsP4wD85y4hc',
    appId: '1:264102339770:ios:77c544b28c80de83cbce83',
    messagingSenderId: '264102339770',
    projectId: 'dormfoodapp',
    storageBucket: 'dormfoodapp.firebasestorage.app',
    iosBundleId: 'com.example.dormfood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANiCfinhpPXZnecaDBg482lFGtShSUUSI',
    appId: '1:264102339770:web:d640c9b90f39036ccbce83',
    messagingSenderId: '264102339770',
    projectId: 'dormfoodapp',
    authDomain: 'dormfoodapp.firebaseapp.com',
    storageBucket: 'dormfoodapp.firebasestorage.app',
  );
}
